server:
    port: 8999
    servlet:
        context-path: /observer

observer:
    info:
        version: 0.0.4
        version-date: 5.29.23
        environment-banner: development
    banner:
        enabled: true
        path: util/banner.txt
    files:
        resources:
            enabled: true
            filename: resources
            filetype: txt
            separate-character: "|"
            comment-character: "//"
        networks:
            enabled: true
            filename: networks
            filetype: txt
            separate-character: "|"
            comment-character: "//"

    httpclient:
        connectionTimeout: 5000
        readTimeout: 10000
        stacktrace:
            enabled: false
