server:
    port: 8999
    servlet:
        context-path: /observer

observer:
    files:
        enabled: true
        filename: resources
        filetype: txt
        separate-character: "|"
        comment-character: "//"

    httpclient:
        connectionTimeout: 5000
        readTimeout: 10000
